version: '3'
services:
  apirest:
    image: apirest
    ports:
      - "8088:8088"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testimagenes
